FROM wazopbx/wazo-base-db
MAINTAINER Wazo Maintainers <dev@wazo.community>

ADD . /usr/src/xivo-auth
WORKDIR /usr/src/xivo-auth

RUN true \
    && python3 setup.py install \
    && pg_start \
    && bin/xivo-auth-init-db --user postgres \
    && (cd /usr/src/xivo-auth && alembic -c alembic.ini upgrade head) \
    && pg_stop \
    && true
USER postgres