FROM wazoplatform/wazo-auth

ENV PYTHONDONTWRITEBYTECODE='true'

COPY integration_tests/assets/external_auth/service_plugin /usr/src/service_plugin
WORKDIR /usr/src/service_plugin
RUN python setup.py install

COPY . /usr/src/wazo-auth
WORKDIR /usr/src/wazo-auth
RUN python3 -m pip install -e .
