FROM wazopbx/wazo-auth

ADD integration_tests/assets/_common/etc/wazo-auth/conf.d /etc/wazo-auth/conf.d
ADD integration_tests/assets/external_auth/service_plugin /usr/src/service_plugin
ADD . /usr/src/wazo-auth
RUN true \
    && cd /usr/src/service_plugin \
    && python setup.py install \
    && cd /usr/src/wazo-auth \
    && python setup.py develop
