services:
  sync:
    depends_on:
      - auth
      - postgres
      - rabbitmq
    environment:
      TARGETS: "auth:9497 postgres:5432 rabbitmq:5672"

  auth:
    volumes:
      - "./etc/wazo-auth/conf.d/asset.metadata.yml:/etc/wazo-auth/conf.d/asset.metadata.yml"
