services:
  sync:
    depends_on:
      - auth
      - auth-worker
      - postgres
      - rabbitmq
    environment:
      TARGETS: "auth:9497 postgres:5432 rabbitmq:5672"

  auth:
    volumes:
      - "./etc/wazo-auth/conf.d/asset.kernel_workers.yml:/etc/wazo-auth/conf.d/asset.kernel_workers.yml"

  auth-worker:
    image: wazoplatform/wazo-auth-tests
    network_mode: "service:auth"
    command: ["sh", "-ec", "wazo-auth-wait; exec wazo-auth --http-worker"]
    environment:
      TZ: UTC+1
      XIVO_UUID: the-predefined-xivo-uuid
      OAUTHLIB_INSECURE_TRANSPORT: 1
      SQLALCHEMY_WARN_20: 1
    volumes:
      - "../..:/usr/src/wazo-auth"
      - "./etc/wazo-auth/conf.d/50-default.yml:/etc/wazo-auth/conf.d/50-default.yml"
      - "./etc/wazo-auth/conf.d/asset.kernel_workers.yml:/etc/wazo-auth/conf.d/asset.kernel_workers.yml"
      - "./var/lib/wazo-auth/saml:/var/lib/wazo-auth/saml:ro"
    depends_on:
      - auth
    deploy:
      replicas: ${INTEGRATION_TEST_AUTH_WORKERS:-1}
